import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
});

const Aadhunik = localFont({
  src: [
    {
      path: "./fonts/Aadhunik.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-aadhunik",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
